"""add project slugs

Revision ID: ec86f3182200
Revises: 23330585b317
Create Date: 2026-09-14 13:49:48.426886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec86f3182200'
down_revision: Union[str, Sequence[str], None] = '23330585b317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "projects",
        sa.Column(
            "slug",
            sa.String(length=180),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE projects
        SET slug = LOWER(
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    TRIM(title),
                    '[^a-zA-Z0-9]+',
                    '-',
                    'g'
                ),
                '(^-|-$)',
                '',
                'g'
            )
        )
        WHERE slug IS NULL
        """
    )

    op.alter_column(
        "projects",
        "slug",
        nullable=False,
    )

    op.create_index(
        op.f("ix_projects_slug"),
        "projects",
        ["slug"],
        unique=True,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_column('projects', 'slug')
    # ### end Alembic commands ###
